server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-catalog
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  zipkin:
    baseUrl: http://localhost:9411/
  data:
    mongodb:
      username: usr-catalog-mongo
      password: pwd-catalog-mongo
      database: catalog-dev-mongo
      port: 27017
      host: localhost

  jpa:
    generate-ddl: true
    hibernate:
      enable_lazy_load_no_trans: true
      event:
        merge:
          entity_copy_observer: allow
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    show-sql: false

info:
  application:
    name: api-catalog

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  retry:
    configs:
      default:
        max-retry-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - java.io.IOException
          - java.net.SocketTimeoutException
      instances:
        retryCustomerRegister:
          base-config: default
          max-retry-attempts: 5
          wait-duration: 2s
          retry-exceptions:
            - java.net.ConnectException
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 30s
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 50
    instances:
      registerCustomer:
        base-config: default
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        wait-duration-in-open-state: 1m
        failure-rate-threshold: 20
